### ISSUE TITLE
plugin-Freemail: Inbox StackOverflowError

### ISSUE THREAD

**Issue by Olezha** [Olezha/fred#1]
Freemail/Inbox:
```
Sep 30, 2020 (freenet.clients.http.ToadletContextImpl, HTTP socket handler@1089706195(91), ERROR): Caught error: java.lang.StackOverflowError handling socket
java.lang.StackOverflowError
```

```
Internal error: please report

java.lang.StackOverflowError
	at java.base/java.lang.String.toUpperCase(String.java:2584)
	at java.base/java.lang.String.toUpperCase(String.java:2608)
	at org.freenetproject.freemail.ui.web.InboxToadlet$SortField.fromString(InboxToadlet.java:386)
	at org.freenetproject.freemail.ui.web.InboxToadlet$SortField.fromString(InboxToadlet.java:386)
	at org.freenetproject.freemail.ui.web.InboxToadlet$SortField.fromString(InboxToadlet.java:386)
	at org.freenetproject.freemail.ui.web.InboxToadlet$SortField.fromString(InboxToadlet.java:386)
	at org.freenetproject.freemail.ui.web.InboxToadlet$SortField.fromString(InboxToadlet.java:386)
```

**Comment by Olezha** [comment]
https://github.com/freenet/plugin-Freemail/pull/41#discussion_r500312660
